BR python-enum34
thus fixing build when with_doc is disabled:

+ oslo-config-generator --config-file tools/config/config-generator.mistral.conf --output-file etc/mistral.conf.sample
Traceback (most recent call last):
  File "/usr/bin/oslo-config-generator", line 6, in <module>
    from oslo_config.generator import main
  File "/usr/lib/python2.7/site-packages/oslo_config/generator.py", line 39, in <module>
    from oslo_config import cfg
  File "/usr/lib/python2.7/site-packages/oslo_config/cfg.py", line 499, in <module>
    import enum
ImportError: No module named enum

This could be a runtime deps of oslo_config

Change-Id: I8b1771231a4b85bcc4f3383cd3446e3a73c798df